In [2]:
import os
import numpy as np
import pandas as pd

In [4]:
# Import results
RESULTS_PATH = os.path.join('..', 'data', 'results')

pca_df = pd.read_csv(os.path.join(RESULTS_PATH, 'pcr_results.csv'))
pca_df

   num_components          mse
0             1.0  4524.018520
1             2.0   516.873620
2             3.0   484.869192
3             5.0   481.270942
4            10.0   426.216375
5            15.0   412.171071
6            20.0   399.109070
7            25.0   366.782639
8            50.0   307.355949
9           100.0   231.751525

In [5]:
aenn_df = pd.read_csv(os.path.join(RESULTS_PATH, 'aenn_results.csv'))
aenn_df

   activation      layers  num_epochs          mse
0        relu        deep          10  1074.289408
1        relu        deep         100  1074.289408
2        relu        deep        1000  1074.289408
3        relu        deep       10000  1074.289408
4        relu      medium          10  1742.411749
5        relu      medium         100  1742.411749
6        relu      medium        1000  1742.411749
7        relu      medium       10000  1742.411749
8        relu     shallow          10  1732.283164
9        relu     shallow         100  1732.283164
10       relu     shallow        1000  1732.283164
11       relu     shallow       10000  1732.283164
12       relu  sigmoidOut         100  1742.411749
13    sigmoid        deep          10     5.665386
14    sigmoid        deep         100     5.665386
15    sigmoid        deep        1000     5.665386
16    sigmoid        deep       10000     5.665386
17    sigmoid      medium          10     5.653316
18    sigmoid      medium         100     5.653316
19    sigmoid      medium        1000     5.653316
20    sigmoid      medium       10000     5.653316
21    sigmoid     shallow          10     5.649318
22    sigmoid     shallow         100     5.649318
23    sigmoid     shallow        1000     5.649318
24    sigmoid     shallow       10000     5.649318
25    sigmoid   symmetric         100     5.653316

In [22]:
# Clean up PCA table
pca_df['method'] = 'pca'
pca_df['description'] = pca_df['num_components'].astype(int).astype(str) + " components"

pca_df[['method', 'description', 'mse']]

  method     description          mse
0    pca    1 components  4524.018520
1    pca    2 components   516.873620
2    pca    3 components   484.869192
3    pca    5 components   481.270942
4    pca   10 components   426.216375
5    pca   15 components   412.171071
6    pca   20 components   399.109070
7    pca   25 components   366.782639
8    pca   50 components   307.355949
9    pca  100 components   231.751525

In [19]:
# Clean up aenn table
aenn_df['method'] = 'autoencoder'
aenn_df['description'] = \
    aenn_df['activation'] + ", " + \
    aenn_df['layers'] + ", " + \
    aenn_df['num_epochs'].astype(str) + " epochs"

aenn_df[['method', 'description', 'mse']]

         method                     description          mse
0   autoencoder           relu, deep, 10 epochs  1074.289408
1   autoencoder          relu, deep, 100 epochs  1074.289408
2   autoencoder         relu, deep, 1000 epochs  1074.289408
3   autoencoder        relu, deep, 10000 epochs  1074.289408
4   autoencoder         relu, medium, 10 epochs  1742.411749
5   autoencoder        relu, medium, 100 epochs  1742.411749
6   autoencoder       relu, medium, 1000 epochs  1742.411749
7   autoencoder      relu, medium, 10000 epochs  1742.411749
8   autoencoder        relu, shallow, 10 epochs  1732.283164
9   autoencoder       relu, shallow, 100 epochs  1732.283164
10  autoencoder      relu, shallow, 1000 epochs  1732.283164
11  autoencoder     relu, shallow, 10000 epochs  1732.283164
12  autoencoder    relu, sigmoidOut, 100 epochs  1742.411749
13  autoencoder        sigmoid, deep, 10 epochs     5.665386
14  autoencoder       sigmoid, deep, 100 epochs     5.665386
15  autoencoder      sigmoid, deep, 1000 epochs     5.665386
16  autoencoder     sigmoid, deep, 10000 epochs     5.665386
17  autoencoder      sigmoid, medium, 10 epochs     5.653316
18  autoencoder     sigmoid, medium, 100 epochs     5.653316
19  autoencoder    sigmoid, medium, 1000 epochs     5.653316
20  autoencoder   sigmoid, medium, 10000 epochs     5.653316
21  autoencoder     sigmoid, shallow, 10 epochs     5.649318
22  autoencoder    sigmoid, shallow, 100 epochs     5.649318
23  autoencoder   sigmoid, shallow, 1000 epochs     5.649318
24  autoencoder  sigmoid, shallow, 10000 epochs     5.649318
25  autoencoder  sigmoid, symmetric, 100 epochs     5.653316

In [25]:
# Final results table
pd.concat([
    pca_df[['method', 'description', 'mse']],
    aenn_df[['method', 'description', 'mse']]
]) \
    .sort_values(by='mse') \
    .to_latex()

'\\begin{tabular}{lllr}\n\\toprule\n{} &       method &                     description &          mse \\\\\n\\midrule\n23 &  autoencoder &   sigmoid, shallow, 1000 epochs &     5.649318 \\\\\n24 &  autoencoder &  sigmoid, shallow, 10000 epochs &     5.649318 \\\\\n21 &  autoencoder &     sigmoid, shallow, 10 epochs &     5.649318 \\\\\n22 &  autoencoder &    sigmoid, shallow, 100 epochs &     5.649318 \\\\\n25 &  autoencoder &  sigmoid, symmetric, 100 epochs &     5.653316 \\\\\n19 &  autoencoder &    sigmoid, medium, 1000 epochs &     5.653316 \\\\\n17 &  autoencoder &      sigmoid, medium, 10 epochs &     5.653316 \\\\\n18 &  autoencoder &     sigmoid, medium, 100 epochs &     5.653316 \\\\\n20 &  autoencoder &   sigmoid, medium, 10000 epochs &     5.653316 \\\\\n16 &  autoencoder &     sigmoid, deep, 10000 epochs &     5.665386 \\\\\n15 &  autoencoder &      sigmoid, deep, 1000 epochs &     5.665386 \\\\\n14 &  autoencoder &       sigmoid, deep, 100 epochs &     5.665386 \\\\\n13 &  autoencoder &        sigmoid, deep, 10 epochs &     5.665386 \\\\\n9  &          pca &                  100 components &   231.751525 \\\\\n8  &          pca &                   50 components &   307.355949 \\\\\n7  &          pca &                   25 components &   366.782639 \\\\\n6  &          pca &                   20 components &   399.109070 \\\\\n5  &          pca &                   15 components &   412.171071 \\\\\n4  &          pca &                   10 components &   426.216375 \\\\\n3  &          pca &                    5 components &   481.270942 \\\\\n2  &          pca &                    3 components &   484.869192 \\\\\n1  &          pca &                    2 components &   516.873620 \\\\\n3  &  autoencoder &        relu, deep, 10000 epochs &  1074.289408 \\\\\n2  &  autoencoder &         relu, deep, 1000 epochs &  1074.289408 \\\\\n1  &  autoencoder &          relu, deep, 100 epochs &  1074.289408 \\\\\n0  &  autoencoder &           relu, deep, 10 epochs &  1074.289408 \\\\\n8  &  autoencoder &        relu, shallow, 10 epochs &  1732.283164 \\\\\n9  &  autoencoder &       relu, shallow, 100 epochs &  1732.283164 \\\\\n10 &  autoencoder &      relu, shallow, 1000 epochs &  1732.283164 \\\\\n11 &  autoencoder &     relu, shallow, 10000 epochs &  1732.283164 \\\\\n7  &  autoencoder &      relu, medium, 10000 epochs &  1742.411749 \\\\\n6  &  autoencoder &       relu, medium, 1000 epochs &  1742.411749 \\\\\n5  &  autoencoder &        relu, medium, 100 epochs &  1742.411749 \\\\\n4  &  autoencoder &         relu, medium, 10 epochs &  1742.411749 \\\\\n12 &  autoencoder &    relu, sigmoidOut, 100 epochs &  1742.411749 \\\\\n0  &          pca &                    1 components &  4524.018520 \\\\\n\\bottomrule\n\\end{tabular}\n'